{
 "title": "Yupana Dev",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yupana_kafka_errors_total" }
   ]
  },
  {
   "title": "Hosts Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(yupana_hosts_count_total)", "legendFormat": "Total Hosts " },
    {
     "expr": "yupana_hosts_count_total{source=\"qpc\"}",
     "legendFormat": "Total QPC Hosts"
    },
    {
     "expr": "yupana_hosts_count_total{source=\"satellite\"}",
     "legendFormat": "Total Satellite Hosts "
    },
    {
     "expr": "sum(increase(yupana_hosts_count_total[1m]))",
     "legendFormat": "Hosts per minute"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"qpc\"}[1m])",
     "legendFormat": "QPC hosts per minute"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"satellite\"}[1m])",
     "legendFormat": "Satellite hosts per minute"
    },
    {
     "expr": "sum(increase(yupana_hosts_count_total[1h]))",
     "legendFormat": "Hosts per hour"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"qpc\"}[1h])",
     "legendFormat": "QPC hosts per hour"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"satellite\"}[1h])",
     "legendFormat": "Satellite hosts per hour"
    },
    {
     "expr": "sum(rate(yupana_hosts_count_total[1h]))",
     "legendFormat": "Rate of hosts per hour"
    },
    {
     "expr": "sum(increase(yupana_hosts_count_total[24h]))",
     "legendFormat": "Hosts uploaded over the last day"
    }
   ]
  },
  {
   "title": "Requests per minute by Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Retries ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "time_retries_total", "legendFormat": "Time Retries" },
    { "expr": "commit_retries_total", "legendFormat": "Commit Retries" },
    {
     "expr": "time_retries_total + commit_retries_total",
     "legendFormat": "Total Retries"
    }
   ]
  },
  {
   "title": "Archived Reports & Slices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "archived_fail_reports_total", "legendFormat": "Archived Failed Reports" },
    { "expr": "archived_success_reports_total", "legendFormat": "Archived Successful Reports" },
    {
     "expr": "archived_fail_reports_total + archived_success_reports_total",
     "legendFormat": "Total Archived Reports"
    },
    {
     "expr": "archived_success_slices_total",
     "legendFormat": "Archived Successful Report Slices"
    },
    { "expr": "archived_fail_slices_total", "legendFormat": "Archived Failed Report Slices" },
    {
     "expr": "archived_success_slices_total + archived_fail_slices_total",
     "legendFormat": "Total Archived Report Slices"
    }
   ]
  },
  {
   "title": "Failed Reports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "failed_validation_total", "legendFormat": "Reports that failed validation" },
    {
     "expr": "failed_download_total",
     "legendFormat": "Reports that failed to download"
    },
    { "expr": "invalid_reports_total", "legendFormat": "Invalid reports " }
   ]
  },
  {
   "title": "Report Processing Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(report_processing_latency_sum)/sum(report_processing_latency_count)",
     "legendFormat": "Report Processing Latency Average"
    },
    {
     "expr": "sum(validation_latency_sum)/sum(validation_latency_count)",
     "legendFormat": "Validation Latency Average"
    },
    {}
   ]
  },
  {
   "title": "Hosts per report (Gauge)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hosts_per_qpc_rep", "legendFormat": "Hosts per QPC report" },
    { "expr": "hosts_per_sat_rep", "legendFormat": "Hosts per SAT report" },
    {
     "expr": "hosts_per_qpc_rep + hosts_per_sat_rep",
     "legendFormat": "Total hosts"
    }
   ]
  },
  {
   "title": "Report Uploads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yupana_message_uploads_total", "legendFormat": "Total report uploads" },
    {
     "expr": "rate(yupana_message_uploads_total[1m])",
     "legendFormat": "Rate of report uploads per minute"
    },
    {
     "expr": "increase(yupana_message_uploads_total[1m])",
     "legendFormat": "Total report uploads per min"
    },
    {
     "expr": "increase(yupana_message_uploads_total[1h])",
     "legendFormat": "Total report uploads per hour"
    },
    {
     "expr": "rate(yupana_message_uploads_total[1h])",
     "legendFormat": "Rate of report uploads per hour"
    },
    {
     "expr": "increase(yupana_message_uploads_total[24h])",
     "legendFormat": "Report uploads over the last day"
    }
   ]
  },
  {
   "title": "Queued Reports & Slices",
   "type": "graph",
   "description": "Visualization of all of the queued reports & report slices",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "queued_report_slices", "legendFormat": "Queued report slices" },
    { "expr": "queued_reports", "legendFormat": "Queued reports" },
    {
     "expr": "increase(queued_report_slices[1m])",
     "legendFormat": "Queued report slices per minute"
    },
    { "expr": "increase(queued_reports[1m])", "legendFormat": "Queued reports per minute" },
    {
     "expr": "rate(queued_report_slices[1m])",
     "legendFormat": "Rate of queued report slices per minute"
    },
    {
     "expr": "rate(queued_reports[1m])",
     "legendFormat": "Rate of queued reports per minute"
    }
   ]
  }
 ]
}