# Generated by Django 2.2 on 2019-05-07 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_platform_id', models.CharField(max_length=50, null=True)),
                ('report_version', models.CharField(max_length=50, null=True)),
                ('report_type', models.CharField(max_length=20, null=True)),
                ('report_id', models.IntegerField(null=True)),
                ('rh_account', models.CharField(max_length=50, null=True)),
                ('upload_ack_status', models.CharField(max_length=10, null=True)),
                ('upload_srv_kafka_msg', models.TextField(null=True)),
                ('git_commit', models.CharField(max_length=50, null=True)),
                ('ready_to_archive', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('NEW', 'new'), ('STARTED', 'started'), ('DOWNLOADED', 'downloaded'), ('FAILED_DOWNLOAD', 'failed to download'), ('VALIDATED', 'validated'), ('FAILED_VALIDATION', 'failed validation'), ('VALIDATION_REPORTED', 'validation reported'), ('FAILED_VALIDATION_REPORTING', 'failed to report validation')], default='new', max_length=28)),
                ('retry_type', models.CharField(choices=[('TIME', 'time'), ('GIT_COMMIT', 'git commit')], default='time', max_length=10)),
                ('state_info', models.TextField(null=True)),
                ('retry_count', models.PositiveSmallIntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_platform_id', models.CharField(max_length=50, null=True)),
                ('report_version', models.CharField(max_length=50, null=True)),
                ('report_type', models.CharField(max_length=20, null=True)),
                ('report_id', models.IntegerField(null=True)),
                ('rh_account', models.CharField(max_length=50, null=True)),
                ('upload_ack_status', models.CharField(max_length=10, null=True)),
                ('upload_srv_kafka_msg', models.TextField(null=True)),
                ('git_commit', models.CharField(max_length=50, null=True)),
                ('ready_to_archive', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('NEW', 'new'), ('STARTED', 'started'), ('DOWNLOADED', 'downloaded'), ('FAILED_DOWNLOAD', 'failed to download'), ('VALIDATED', 'validated'), ('FAILED_VALIDATION', 'failed validation'), ('VALIDATION_REPORTED', 'validation reported'), ('FAILED_VALIDATION_REPORTING', 'failed to report validation')], default='new', max_length=28)),
                ('retry_type', models.CharField(choices=[('TIME', 'time'), ('GIT_COMMIT', 'git commit')], default='time', max_length=10)),
                ('state_info', models.TextField(null=True)),
                ('retry_count', models.PositiveSmallIntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSliceArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_platform_id', models.CharField(max_length=50, null=True)),
                ('report_slice_id', models.CharField(max_length=50, null=True)),
                ('rh_account', models.CharField(max_length=50, null=True)),
                ('report_json', models.TextField(null=True)),
                ('git_commit', models.CharField(max_length=50, null=True)),
                ('ready_to_archive', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('PENDING', 'pending'), ('NEW', 'new'), ('RETRY_VALIDATION', 'retry_validation'), ('FAILED_VALIDATION', 'failed_validation'), ('VALIDATED', 'validated'), ('STARTED', 'started'), ('HOSTS_UPLOADED', 'hosts uploaded'), ('FAILED_HOSTS_UPLOAD', 'failed to upload hosts')], default='new', max_length=28)),
                ('retry_type', models.CharField(choices=[('TIME', 'time'), ('GIT_COMMIT', 'git commit')], default='time', max_length=10)),
                ('state_info', models.TextField(null=True)),
                ('retry_count', models.PositiveSmallIntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('failed_hosts', models.TextField(null=True)),
                ('candidate_hosts', models.TextField(null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ReportArchive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_platform_id', models.CharField(max_length=50, null=True)),
                ('report_slice_id', models.CharField(max_length=50, null=True)),
                ('rh_account', models.CharField(max_length=50, null=True)),
                ('report_json', models.TextField(null=True)),
                ('git_commit', models.CharField(max_length=50, null=True)),
                ('ready_to_archive', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('PENDING', 'pending'), ('NEW', 'new'), ('RETRY_VALIDATION', 'retry_validation'), ('FAILED_VALIDATION', 'failed_validation'), ('VALIDATED', 'validated'), ('STARTED', 'started'), ('HOSTS_UPLOADED', 'hosts uploaded'), ('FAILED_HOSTS_UPLOAD', 'failed to upload hosts')], default='new', max_length=28)),
                ('retry_type', models.CharField(choices=[('TIME', 'time'), ('GIT_COMMIT', 'git commit')], default='time', max_length=10)),
                ('state_info', models.TextField(null=True)),
                ('retry_count', models.PositiveSmallIntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('failed_hosts', models.TextField(null=True)),
                ('candidate_hosts', models.TextField(null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
