# Generated by Django 2.1.7 on 2019-02-18 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_platform_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('upload_srv_kafka_msg', models.TextField(null=True)),
                ('report_json', models.TextField(null=True)),
                ('state', models.CharField(choices=[('new', 'new'), ('started', 'started'), ('downloaded', 'downloaded'), ('failed to download', 'failed to download'), ('validated', 'validated'), ('failed validation', 'failed validation'), ('validation reported', 'validation reported'), ('failed to report validation', 'failed to report validation'), ('hosts uploaded', 'hosts uploaded'), ('failed to upload hosts', 'failed to upload hosts')], default='new', max_length=28)),
                ('stage_info', models.TextField()),
                ('retry_count', models.IntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('failed_hosts', models.TextField()),
                ('candidate_hosts', models.TextField()),
            ],
        ),
    ]
