# Generated by Django 2.1.7 on 2019-02-18 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_platform_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('upload_srv_kafka_msg', models.TextField(null=True)),
                ('report_json', models.TextField(null=True)),
                ('state', models.CharField(choices=[('NEW', 'new'), ('STARTED', 'started'), ('DOWNLOADED', 'downloaded'), ('FAILED_DOWNLOAD', 'failed to download'), ('VALIDATED', 'validated'), ('FAILED_VALIDATION', 'failed validation'), ('VALIDATION_REPORTED', 'validation reported'), ('FAILED_VALIDATION_REPORTING', 'failed to report validation'), ('HOSTS_UPLOADED', 'hosts uploaded'), ('FAILED_HOSTS_UPLOAD', 'failed to upload hosts')], default='new', max_length=28)),
                ('state_info', models.TextField()),
                ('retry_count', models.PositiveSmallIntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('failed_hosts', models.TextField()),
                ('candidate_hosts', models.TextField()),
            ],
        ),
    ]
