# Generated by Django 2.2 on 2019-04-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190423_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportslice',
            name='upload_ack_status',
        ),
        migrations.RemoveField(
            model_name='reportslice',
            name='upload_srv_kafka_msg',
        ),
        migrations.RemoveField(
            model_name='reportslicearchive',
            name='upload_ack_status',
        ),
        migrations.RemoveField(
            model_name='reportslicearchive',
            name='upload_srv_kafka_msg',
        ),
    ]
