# Generated by Django 2.2 on 2019-04-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190430_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_slices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ReportSlice'),
        ),
        migrations.AlterField(
            model_name='reportarchive',
            name='report_slices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ReportSlice'),
        ),
    ]
