# Generated by Django 2.2.13 on 2022-05-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_legacy_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='org_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportarchive',
            name='org_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportslice',
            name='org_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportslicearchive',
            name='org_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
