# Generated by Django 2.2 on 2019-04-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190430_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_slices',
        ),
        migrations.RemoveField(
            model_name='reportarchive',
            name='report_slices',
        ),
        migrations.AddField(
            model_name='reportslice',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Report'),
        ),
        migrations.AddField(
            model_name='reportslicearchive',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Report'),
        ),
    ]
