{
 "title": "subscriptions-qa",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Database Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yupana_db_errors_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "DB errors"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yupana_kafka_errors_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "kafka errors"
    }
   ]
  },
  {
   "title": "Hosts Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yupana_hosts_count_tota{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total Hosts "
    },
    {
     "expr": "sum(yupana_hosts_count_total{source=\"qpc\", kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total QPC Hosts"
    },
    {
     "expr": "sum(yupana_hosts_count_total{source=\"satellite\", kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total Satellite Hosts "
    },
    {
     "expr": "sum(increase(yupana_hosts_count_total{kubernetes_namespace=\"subscriptions-qa\"}[1m]))",
     "legendFormat": "Hosts per minute"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"qpc\", kubernetes_namespace=\"subscriptions-qa\"}[1m])",
     "legendFormat": "QPC hosts per minute"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"satellite\", kubernetes_namespace=\"subscriptions-qa\"}[1m])",
     "legendFormat": "Satellite hosts per minute"
    },
    {
     "expr": "sum(increase(yupana_hosts_count_total{kubernetes_namespace=\"subscriptions-qa\"}[1h]))",
     "legendFormat": "Hosts per hour"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"qpc\", kubernetes_namespace=\"subscriptions-qa\"}[1h])",
     "legendFormat": "QPC hosts per hour"
    },
    {
     "expr": "increase(yupana_hosts_count_total{source=\"satellite\", kubernetes_namespace=\"subscriptions-ci\"}[1h])",
     "legendFormat": "Satellite hosts per hour"
    },
    {
     "expr": "sum(rate(yupana_hosts_count_total{kubernetes_namespace=\"subscriptions-qa\"}[1h]))",
     "legendFormat": "Rate of hosts per hour"
    },
    {
     "expr": "sum(increase(yupana_hosts_count_total{kubernetes_namespace=\"subscriptions-qa\"}[24h]))",
     "legendFormat": "Hosts uploaded over the last day"
    }
   ]
  },
  {
   "title": "Requests per minute by Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total{kubernetes_namespace=\"subscriptions-qa\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Retries ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(time_retries_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Time Retries"
    },
    {
     "expr": "sum(commit_retries_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Commit Retries"
    },
    {
     "expr": "sum(time_retries_total{kubernetes_namespace=\"subscriptions-qa\"}) + sum(commit_retries_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total Retries"
    }
   ]
  },
  {
   "title": "Archived Reports & Slices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(archived_fail_reports_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Archived Failed Reports"
    },
    {
     "expr": "sum(archived_success_reports_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Archived Successful Reports"
    },
    {
     "expr": "sum(archived_fail_reports_total{kubernetes_namespace=\"subscriptions-qa\"}) + sum(archived_success_reports_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total Archived Reports"
    },
    {
     "expr": "sum(archived_success_slices_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Archived Successful Report Slices"
    },
    {
     "expr": "sum(archived_fail_slices_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Archived Failed Report Slices"
    },
    {
     "expr": "sum(archived_success_slices_total{kubernetes_namespace=\"subscriptions-qa\"}) + sum(archived_fail_slices_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total Archived Report Slices"
    }
   ]
  },
  {
   "title": "Failed Reports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(failed_validation_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Reports that failed validation"
    },
    {
     "expr": "sum(failed_download_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Reports that failed to download"
    },
    {
     "expr": "sum(invalid_reports_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Invalid reports "
    }
   ]
  },
  {
   "title": "Report Processing Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(report_processing_latency_sum{kubernetes_namespace=\"subscriptions-qa\"})/sum(report_processing_latency_count{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Report Processing Latency Average"
    },
    {
     "expr": "sum(validation_latency_sum{kubernetes_namespace=\"subscriptions-qa\"})/sum(validation_latency_count{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Validation Latency Average"
    }
   ]
  },
  {
   "title": "Hosts per report (Gauge)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hosts_per_qpc_rep{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Hosts per QPC report"
    },
    {
     "expr": "sum(hosts_per_sat_rep{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Hosts per SAT report"
    },
    {
     "expr": "sum(hosts_per_qpc_rep{kubernetes_namespace=\"subscriptions-qa\"}) + sum(hosts_per_sat_rep{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total hosts"
    }
   ]
  },
  {
   "title": "Report Uploads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yupana_message_uploads_total{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Total report uploads"
    },
    {
     "expr": "sum(rate(yupana_message_uploads_total{kubernetes_namespace=\"subscriptions-qa\"}[1m]))",
     "legendFormat": "Rate of report uploads per minute"
    },
    {
     "expr": "sum(increase(yupana_message_uploads_total{kubernetes_namespace=\"subscriptions-qa\"}[1m]))",
     "legendFormat": "Total report uploads per min"
    },
    {
     "expr": "sum(increase(yupana_message_uploads_total{kubernetes_namespace=\"subscriptions-qa\"}[1h]))",
     "legendFormat": "Total report uploads per hour"
    },
    {
     "expr": "sum(rate(yupana_message_uploads_total{kubernetes_namespace=\"subscriptions-qa\"}[1h]))",
     "legendFormat": "Rate of report uploads per hour"
    },
    {
     "expr": "sum(increase(yupana_message_uploads_total{kubernetes_namespace=\"subscriptions-qa\"}[24h]))",
     "legendFormat": "Report uploads over the last day"
    }
   ]
  },
  {
   "title": "Queued Reports & Slices",
   "type": "graph",
   "description": "Visualization of all of the queued reports & report slices",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(queued_report_slices{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Queued report slices"
    },
    {
     "expr": "sum(queued_reports{kubernetes_namespace=\"subscriptions-qa\"})",
     "legendFormat": "Queued reports"
    },
    {
     "expr": "sum(increase(queued_report_slices{kubernetes_namespace=\"subscriptions-qa\"}[1m]))",
     "legendFormat": "Queued report slices per minute"
    },
    {
     "expr": "sum(increase(queued_reports[1m]))",
     "legendFormat": "Queued reports per minute"
    },
    {
     "expr": "sum(rate(queued_report_slices{kubernetes_namespace=\"subscriptions-qa\"}[1m]))",
     "legendFormat": "Rate of queued report slices per minute"
    },
    {
     "expr": "sum(rate(queued_reports{kubernetes_namespace=\"subscriptions-qa\"}[1m]))",
     "legendFormat": "Rate of queued reports per minute"
    }
   ]
  }
 ]
}