openapi: "3.0.0"
info:
  description: "Host object of host inventory used for the Quipucords and Satellite servers."
  version: 1.0.0
  title: Swagger Host
  contact:
    email: "quipucords@redhat.com"
  license:
    name: "GPL 3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.txt"

securityDefinitions:
  Token:
    type: apiKey
    name: Authorization
    in: header
security:
  - Token: []
  
components:
  schemas:
    InsightsReport:
      properties:
        metadata_tar_path:
          type: object
          properties:
            report_id:
              type: "string"
              description: "Globally unique uuid for report"
              example: "be3075ac-84d3-4b62-9f5c-a418a36f802d"
            host_inventory_api_version:
              type: "string"
              description: "Host inventory API version"
              example: "1.0"
            source:
              type: "string"
              description: "Source where the report is generated"
              example: "qpc"
            source_metadata:
              type: object
              description: "This object is intended to allow the sender to include any data they find useful for tracking. The service will log the contents of this object. No validation is performed on the contents of source_metadata."
              example: {
                  "report_platform_id": "afc1a6e4-2c44-496c-96e0-b6f94c5b9cd2",
                  "report_type": "insights",
                  "report_version": "1.0.0.7858056",
                  "qpc_server_report_id": 4,
                  "qpc_server_version": "1.0.0.7858056",
                  "qpc_server_id": "ac90a01c-aaae-4c4f-ae60-f058fcdf794f"
              }
            report_slices:
              type: object
              properties:
                report_slice_id:
                  $ref: "#/components/schemas/InsightsReportSliceMetadata"
              description: "Metadata for each report slice"
          description: "Metadata describing report contents"
        report_slice_tar_path:
          type: object
          properties:
            report_slice_id:
              type: "string"
              description: "The Insights report slice identifier"
              example: "abc075ac-84d3-4b62-9f5c-a418a36f802d"
            hosts:
              type: "array"
              items:
                $ref: "https://raw.githubusercontent.com/RedHatInsights/insights-host-inventory/system_profile_changes/swagger/api.spec.yaml#components/schemas/CreateHostIn"
              description: "List of the hosts scanned (refers to Host object in Insights' api.spec.yaml file)"
          description: "Slices of the Insights report"
    InsightsReportSliceMetadata:
      properties:
        number_hosts:
          type: "integer"
          format: "int64"
          description: "The number of hosts in this slice"
          example: 116
          