openapi: "3.0.0"
info:
  description: "Report slices of host inventory used for the Quipucords and Satellite servers."
  version: 1.0.0
  title: Swagger Report Slices
  contact:
    email: "quipucords@redhat.com"
  license:
    name: "GPL 3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.txt"

paths:
  /dummy:
    get:
      operationId: api.dummy
      tags:
        - dummy
      summary: Does not do anything
      description: This path does not work. It is fake path created to avoid validation errors in swagger file
      responses:
        '200':
          description: Just a dummy path

components:
  schemas:
    ReportSlice:
      type: object
      properties:
        report_slice_id:
          type: "string"
          description: "The Insights report slice identifier"
          example: "abc075ac-84d3-4b62-9f5c-a418a36f802d"
        hosts:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/RedHatInsights/insights-host-inventory/system_profile_changes/swagger/api.spec.yaml#components/schemas/CreateHostIn"
          description: "List of the hosts scanned (refers to Host object in Insights' api.spec.yaml file)"
      description: "Slices of the Insights report"
          