openapi: "3.0.0"
info:
  description: "Report slices of host inventory used for the Quipucords and Satellite servers."
  version: 1.0.0
  title: Swagger Report Slices
  contact:
    email: "quipucords@redhat.com"
  license:
    name: "GPL 3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.txt"

paths:
  /dummy:
    get:
      operationId: api.dummy
      tags:
        - dummy
      summary: Does not do anything
      description: This path does not work. It is fake path created to avoid validation errors in swagger file
      responses:
        '200':
          description: Just a dummy path

components:
  schemas:
    ReportSlice:
      type: object
      properties:
        report_slice_id:
          type: "string"
          description: "The Insights report slice identifier"
          example: "abc075ac-84d3-4b62-9f5c-a418a36f802d"
        insights_id:
          description: >-
            An ID defined in /etc/insights-client/machine-id. This field is
            considered a canonical fact.
          type: string
          format: uuid
          example: 3f01b55457674041b75e41829bcee1dc
          minLength: 32
          maxLength: 36
        rhel_machine_id:
          description: >-
            A Machine ID of a RHEL host.  This field is considered to be a
            canonical fact.
          type: string
          format: uuid
          example: 3f01b55457674041b75e41829bcee1dc
          minLength: 32
          maxLength: 36
        subscription_manager_id:
          description: >-
            A Red Hat Subcription Manager ID of a RHEL host.  This field is
            considered to be a canonical fact.
          type: string
          format: uuid
          example: 3f01b55457674041b75e41829bcee1dc
          minLength: 32
          maxLength: 36
        bios_uuid:
          description: >-
            A UUID of the host machine BIOS.  This field is considered to be a
            canonical fact.
          type: string
          format: uuid
          example: 3f01b55457674041b75e41829bcee1dc
          minLength: 32
          maxLength: 36
        ip_addresses:
          description: >-
            Host’s network IP addresses.  This field is considered to be a
            canonical fact.
          type: array
          items:
            type: string
            format: ip_address
            minLength: 7
            maxLength: 45
          minItems: 1
          example:
            - 10.10.0.1
            - 10.0.0.2
        fqdn:
          description: >-
            A host’s Fully Qualified Domain Name.  This field is considered to
            be a canonical fact.
          type: string
          example: my.host.example.com
          minLength: 1
          maxLength: 255
        mac_addresses:
          description: >-
            Host’s network interfaces MAC addresses.  This field is considered
            to be a canonical fact.
          type: array
          items:
            type: string
            format: mac_address
            minLength: 1
            maxLength: 23
          minItems: 1
          example:
            - 'c2:00:d0:c8:61:01'
        hosts:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/RedHatInsights/insights-host-inventory/system_profile_changes/swagger/api.spec.yaml#components/schemas/CreateHostIn"
          description: "List of the hosts scanned (refers to Host object in Insights' api.spec.yaml file)"
      description: "Slices of the Insights report"
          