#
# This template defines configmaps used to configure Yupana.
#
kind: Template
apiVersion: v1
metadata:
  name: yupana-configmap-template
  annotations:
    openshift.io/display-name: "Yupana"
    description: "Subscription Insights powered by Django+PostgreSQL"
    tags: "quickstart,python,django,postgresql"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to deploy and run the Yupana database."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://yupana.readthedocs.io/en/latest/"
labels:
  app: yupana
  template: yupana-configmap
objects:
# database config
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: yupana-db
    labels:
      name: yupana
  data:
    database-engine: ${DATABASE_ENGINE}
    database-name: ${DATABASE_NAME}
    database-service-name: POSTGRES_SQL
    postgres-sql-service-host: ${POSTGRES_SQL_SERVICE_HOST}
    postgres-sql-service-port: "5432"

# yupana application config
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: yupana-app
    labels:
      name: yupana
  data:
    app-config: ${APP_CONFIG}
    app-home: ${APP_HOME}
    app-module: ${APP_MODULE}
    app-namespace: ${NAMESPACE}
    app-domain: ${APP_DOMAIN}
    build-version: ${BUILD_VERSION}

# kafka queue configs
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: yupana-messaging
    labels:
      name: yupana
  data:
    insights-kafka-server-host: ${KAFKA_HOST}.${KAFKA_NAMESPACE}.svc
    insights-kafka-server-port: ${KAFKA_PORT}
    insights-host-inventory-url: ${INSIGHTS_HOST_INVENTORY_URL}

# application settings configs
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: yupana-env
    labels:
      name: yupana
  data:
    retries-allowed: ${RETRIES_ALLOWED}
    retry-time: ${RETRY_TIME}
    hosts-upload-timeout: ${HOSTS_UPLOAD_TIMEOUT}
    hosts-upload-futures-count: ${HOSTS_UPLOAD_FUTURES_COUNT}
    hosts-per-req: ${HOSTS_PER_REQ}
    max-hosts-per-rep: ${MAX_HOSTS_PER_REP}
    max-threads: ${MAX_THREADS}
    minimum-replicas: ${MINIMUM_REPLICAS}
    maximum-replicas: ${MAXIMUM_REPLICAS}
    target-cpu-utilization: ${TARGET_CPU_UTILIZATION}
    pause-kafka-for-file-upload-service: ${PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE}
    host-inventory-upload-mode: ${HOST_INVENTORY_UPLOAD_MODE}
    new-report-query-interval: ${NEW_REPORT_QUERY_INTERVAL}
    log-level: INFO
parameters:
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: yupana
- description: The Name
  displayName: Name
  name: NAME
  required: true
  value: yupana
- description: Insights Upload Server address
  displayName: Kafka server address
  name: KAFKA_HOST
  required: true
  value: localhost
- description: Insights Upload Server port
  displayName: Kafka server port
  name: KAFKA_PORT
  required: true
  value: "29092"
- description: Insights Upload Server namespace
  displayName: Kafka server namespace
  name: KAFKA_NAMESPACE
  required: true
  value: yupana
- description: 'Database engine: postgresql, mysql or sqlite (default).'
  displayName: Database Engine
  name: DATABASE_ENGINE
  required: true
  value: postgresql
- displayName: Database Name
  name: DATABASE_NAME
  required: true
  value: yupana
- displayName: Database Host
  name: POSTGRES_SQL_SERVICE_HOST
  required: true
- description: Absolute path to application install location (optional).
  displayName: Application Home Directory
  name: APP_HOME
  value: /opt/app-root/src/yupana
- description: Python module name of the application (optional).
  displayName: Application Module Name
  name: APP_MODULE
  value: config.wsgi
- displayName: User Interface Domain
  value: 'project-yupana.com'
  name: APP_DOMAIN
- description: Absolute path to Gunicorn configuration file (optional).
  displayName: Application Configuration File Path
  name: APP_CONFIG
  value: /opt/app-root/src/yupana/gunicorn.py
- displayName: Build Version
  description: The build version
  name: BUILD_VERSION
  required: false
- description: Insights Host Inventory Url
  displayName: Insights Host Inventory
  name: INSIGHTS_HOST_INVENTORY_URL
  required: true
  value: http://127.0.0.1:8000/r/insights/platform/inventory/api/v1/hosts

- description: Retry time in minutes
  displayName: Retry time
  name: RETRY_TIME
  required: false
  value: "480"
- description: Timeout for each host upload
  displayName: Hosts Upload Timeout
  name: HOSTS_UPLOAD_TIMEOUT
  required: false
  value: "120"
- description: The hosts upload future count to wait for at one time
  displayName: Hosts Upload Futures Count
  name: HOSTS_UPLOAD_FUTURES_COUNT
  required: false
  value: "100"
- description: Number of retries allowed
  displayName: Retries allowed
  name: RETRIES_ALLOWED
  required: false
  value: "5"
- description: Hosts to upload per bulk request
  displayName: Hosts per request
  name: HOSTS_PER_REQ
  required: false
  value: "250"
- description: Maximum number of hosts per report slice
  displayName: Max hosts per report slice
  name: MAX_HOSTS_PER_REP
  required: false
  value: "10000"
- description: Max number of threads per pod
  displayName: Max threads
  name: MAX_THREADS
  required: true
  value: "3"
- description: Minimum Replicas for Autoscaling
  displayName: Minimum Replicas
  name: MINIMUM_REPLICAS
  required: true
  value: "1"
- description: Maximum Replicas for Autoscaling
  displayName: Maximum Replicas
  name: MAXIMUM_REPLICAS
  required: true
  value: "10"
- description: Target CPU Utilization Percentage
  displayName: Target CPU Utilization
  name: TARGET_CPU_UTILIZATION
  required: true
  value: "75"
- description: Pause the Kafka consumer for file upload
  displayName: Pause Kafka for file upload
  name: PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE
  required: false
- description: Mode for uploading to the host inventory
  displayName: Host inventory upload mode
  name: HOST_INVENTORY_UPLOAD_MODE
  required: true
  value: "http"
- description: Time to sleep between looking for reports
  displayName: Time in between db queries for reports and slices
  name: NEW_REPORT_QUERY_INTERVAL
  required: false
  value: "60"