kind: Template
apiVersion: v1
metadata:
  name: yupana-configmap-template
  annotations:
    openshift.io/display-name: "Yupana"
    description: "Subscription Insights powered by Django+PostgreSQL"
    tags: "quickstart,python,django,postgresql"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to deploy and run the Yupana database."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://yupana.readthedocs.io/en/latest/"
labels:
  app: yupana
  template: yupana-secret
objects:
# database secrets
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: yupana
      template: yupana-template
    annotations:
      template.openshift.io/expose-database_name: "{.data['database-name']}"
      template.openshift.io/expose-password: "{.data['database-password']}"
      template.openshift.io/expose-username: "{.data['database-user']}"
      template.openshift.io/expose-db_client_cert: "{.data['db-client-cert']}"
    name: ${DATABASE_SERVICE_NAME}
  stringData:
    database-name: ${DATABASE_NAME}
    database-password: ${DATABASE_PASSWORD}
    database-user: ${DATABASE_USER}
    database-admin-password: ${DATABASE_ADMIN_PASSWORD}
    db-client-cert: ${DATABASE_SERVICE_CERT}
# django secrets
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: yupana
      template: yupana-template
    annotations:
      template.openshift.io/expose-django_secret_key: "{.data['django-secret-key']}"
    name: ${NAME}-secret
  stringData:
    django-secret-key: ${DJANGO_SECRET_KEY}

parameters:
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: yupana
- description: The Name
  displayName: Name
  name: NAME
  required: true
  value: yupana
- displayName: Database Name
  name: DATABASE_NAME
  required: true
  value: yupana
- displayName: Database Username
  name: DATABASE_USER
  required: true
  value: yupanaadmin
- displayName: Database User Password
  name: DATABASE_PASSWORD
  required: true
  value: admin123
- displayName: Database Admin Password
  value: admin123
  name: DATABASE_ADMIN_PASSWORD
- description: The database client certificate
  displayName: Database Client Certificate
  name: DATABASE_SERVICE_CERT
  required: false
- displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: yupana-db
- description: Set this to a long random string.
  displayName: Django Secret Key
  from: '[a-zA-Z0-9]{50}'
  generate: expression
  name: DJANGO_SECRET_KEY