apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: postgresql-96-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: centos/postgresql-96-centos7
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: python-36-ubi7
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi7/python-36
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
kind: List
